import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Tabs } from "./components/Tabs";
import { getDictionary } from "@/app/dictionaries";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Morrigames",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  params: { lang: Locales };
  children: React.ReactNode;
}>) {
  const dict = await getDictionary(params.lang);
  return (
    <html>
      <body
        className={`${inter.variable} font-sans antialiased`}
      >
        <div className="bg-white text-gray-900 h-full min-h-[100vh]">
          <Tabs dict={dict.home.tabs} />
          {children}
        </div>
      </body>
    </html>
  );
}
