import type { Metadata } from "next";
import localFont from "next/font/local";
import { Tabs } from "./components/Tabs";
import { getDictionary } from "@/app/dictionaries";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Morrigames",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  params: { lang: Locales };
  children: React.ReactNode;
}>) {
  const dict = await getDictionary(params.lang);
  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-white text-gray-900 h-full min-h-[100vh]">
          <Tabs dict={dict.home.tabs} />
          {children}
        </div>
      </body>
    </html>
  );
}
